steps:
# Decrypt the file containing the key
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - ./scripts/decrypt.sh
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  env:
    - 'BRANCH=$BRANCH_NAME'
  id: 'decrypt-key'

# Set up git with key and domain.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'git-setup'

- name: 'golang:1.15'
  entrypoint: 'bash'
  env:
    - GO111MODULE=on
  args: ['./scripts/get.sh']
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'go-modules'
    path: /go
  wait_for: ['git-setup']
  id: 'get'

- name: 'golang:1.15'
  entrypoint: 'bash'
  env:
    - GO111MODULE=on
  args: ['./scripts/lint.sh']
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'go-modules'
    path: /go
  wait_for: ['get']
  id: 'lint'

- name: 'golang:1.15'
  args: ['go', 'test', '-v', './...', '-race']
  env:
    - GO111MODULE=on
    - CGO_ENABLED=1
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'go-modules'
    path: /go
  wait_for: ['lint']
  id: 'test'

- name: 'golang:1.15'
  args: ['go', 'build', '-o', 'referral', '.']
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'go-modules'
    path: /go
  wait_for: ['lint', 'test']
  id: 'build'

# Buid new docker image.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - ./scripts/build.sh
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'VERSION=1.0.0'
    - 'SHORT_SHA=$SHORT_SHA'
    - 'BRANCH=$BRANCH_NAME'
  id: 'docker-build'
  wait_for: ['build']

# Deploy container image.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - ./scripts/deploy.sh
  id: 'deploy'
  wait_for: ['docker-build']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'VERSION=1.0.0'
    - 'SHORT_SHA=$SHORT_SHA'
    - 'BRANCH=$BRANCH_NAME'
    - 'REGION=asia-southeast1'
# Set build timeout to 20 minutes.
timeout: 1200s