steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['curl', '-H', '"Metadata-Flavor: Google"', 'http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip']
  id: 'curl'

- name: 'golang:1.15'
  args: ['go', 'run', 'main.go']
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
  id: 'run'
