steps:
- name: 'golang:1.15'
  args: ['go', 'test', '-v', './...', '-race']
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0
  id: 'test'

- name: 'golang:1.15'
  args: ['go', 'run', 'main.go']
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
  wait_for: ['test']
  id: 'run'
